[package]
name = "world_generators"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world_generators_core = { path = "../core" }
wasm-bindgen="0.2"

[lib]
crate-type = ["cdylib", "rlib"]

